apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-helm-istio-base
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/matteodalgrande/k8s_argocd.git
    targetRevision: HEAD
    path: helm/istio/base  # <-- source of true into the git repo
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/failurePolicy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
